language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      env: BCMATH='on'
      script:
        - |
          if [[ $BCMATH != 'on' ]]; then
              ls -la ~/.phpenv/src;
              ls -la ~/.phpenv/versions/$(phpenv version-name);
              ls -la ~/.phpenv/versions/$(phpenv version-name)/etc;
          fi
          php -v;
          php -m;
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='off'
