language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      before_install:
        - |
          php -v;
          php -m;
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: PHP_BUILD_CONFIGURE_OPTS="--disable-bcmath"
