language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      env: BCMATH='on'
      script:
        - |
          if [[ $BCMATH != 'on' ]]; then
              git clone https://github.com/php-build/php-build $(phpenv root)/plugins/php-build;
              export PHP_BUILD_CONFIGURE_OPTS="--disable-bcmath"
              phpenv install 7.2
              phpenv rehash
          fi
          php -v;
          php -m;
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='off'
