language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      env: BCMATH='on'
      script:
        - |
          if [[ $BCMATH != 'on' ]]; then
              cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
              cat ~/.phpenv/src/Makefile.in;
              ls -la ~/.phpenv/versions/$(phpenv version-name)/conf.d;
              ls -la ~/.phpenv/versions/$(phpenv version-name)/init.d;
          fi
          php -v;
          php -m;
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='off'
