language: c

branches:
  only:
  - master

# Running builds in parallel for lua 5.2 and 5.3
env:
  - LUA=lua5.2
  - LUA=lua5.3

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install ${LUA}

script:
  - lua ./tests/runall_tests.lua
