language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      script:
        - if [[ $BCMATH != 'on' ]]; then sed -i 's/extension = bcmath.so/#extension = bcmath.so/g' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
        - php -v
        - php -m
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='off'
