language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      env: BCMATH='on'
      script:
        - |
          if [[ $BCMATH != 'on' ]]; then
              sudo apt-get remove php7.2-bcmath;
          fi
          php -v;
          php -m;
          phpenv --help;
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='off'
