language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      env: BCMATH='on'
      script:
        - |
          if [[ $BCMATH != 'on' ]]; then
              wget https://www.php.net/distributions/php-7.2.19.tar.bz2 -O php-7.2.19.tar.bz2
              tar -xvjf php-7.2.19.tar.bz2
              cd php-7.2.19
              ./configure
              make clean
              make
          fi
          php -v;
          php -m;
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='off'
