language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      script:
        - if ['$BCMATH' = 'on']
            echo "extension = <extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
          fi;
        - php -v
        - php -m
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='on'
