language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      script:
        - if [[ $BCMATH != 'on' ]]; then phpenv config-rm bcmath.ini || true; fi
        - php -v
        - php -m
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='off'
