language: php

jobs:
  include:
    - &STANDARD_TEST_JOB
      stage: Test
      php: 7.2
      env: BCMATH='on'
      script:
        - |
          if [[ $BCMATH != 'on' ]]; then
              cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
              ls -la ~/.phpenv/version;
              ls -la ~/.phpenv
          fi
          php -v;
          php -m;
    -
      <<: *STANDARD_TEST_JOB
      php: 7.2
      env: BCMATH='off'
